name: ItemRush
version: 1.0
main: info.z10.itemrush.ItemRush
api-version: 1.20
commands:
  itemrush:
    description: Starts the ItemRush minigame
    usage: /itemrush start
    permission: itemrush.admin
